import { expect, type Page } from '@playwright/test'
import { faker } from '@faker-js/faker'

export const completeIndividualDetailsSection = async (page: Page) => {
    await page.getByRole('link', { name: 'Change Contact details' }).click()
    await page.getByLabel('Building name').click()
    await page.getByLabel('Building name').fill(faker.location.buildingNumber())
    await page.getByRole('region', { name: 'Form content' }).click()
    await page.getByLabel('House number').fill(faker.location.buildingNumber())
    await page.getByLabel('Street name').fill(faker.location.street())
    await page.getByLabel('District').fill(faker.location.city())
    await page.getByLabel('Town or city').fill(faker.location.city())
    await page.getByLabel('County').fill(faker.location.county())
    await page.getByLabel('Postcode').fill(faker.location.zipCode())
    await page.getByLabel('Mobile number').fill(faker.phone.number())
    await page.getByLabel('Phone number').fill(faker.phone.number())
    await page.getByLabel('Email').fill(faker.internet.email())
    await page.getByRole('button', { name: 'Save' }).click()
    await expect(page.locator('#main-content h1')).toHaveText("Individual's details")
    await page.getByRole('button', { name: 'Add contact' }).click()
    await expect(page.locator('#main-content h1')).toHaveText('Emergency contact')
    await page.locator('#emergency_contact_first_name').fill(faker.person.firstName())
    await page.getByLabel('Surname').fill(faker.person.lastName())
    await page.getByLabel('Relationship to the individual').fill('Friend')
    await page.getByLabel('Mobile').fill(faker.phone.number())
    await page.getByLabel('Phone number').fill(faker.phone.number())
    await page.getByRole('button', { name: 'Save' }).click()
    await expect(page.locator('#main-content h1')).toHaveText("Individual's details")
    await page.locator('#individual_details_complete').click()
    await page.getByRole('button', { name: 'Save' }).click()
    await expect(page.locator('li:has-text("Individual\'s details")').first()).toContainText('COMPLETED'.toLowerCase())
    await expect(page.locator('#main-content h1')).toHaveText('Community payback assessment')
}
