name: Format code

on: pull_request

jobs:
  fix-formatting:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          cache: npm

      - run: |
          npm ci
          npx eslint . --fix
          git add .

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}

      - name: Commit and push
        uses: dsanders11/github-app-commit-action@48d2ff8c1a855eb15d16afa97ae12616456d7cbc # v1.4.0
        with:
          fail-on-no-changes: false
          message: Formatting changes
          token: ${{ steps.app-token.outputs.token }}