name: Format code

on: pull_request

jobs:
  fix-formatting:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: actions/setup-node@v6
        with:
          cache: npm

      - run: |
          npm ci
          npx eslint . --fix
          git add .

      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}

      - name: Commit and push
        uses: dsanders11/github-app-commit-action@43de6da2f4d927e997c0784c7a0b61bd19ad6aac # v1.5.0
        with:
          fail-on-no-changes: false
          message: Formatting changes
          token: ${{ steps.app-token.outputs.token }}