name: Format code

on:
  pull_request:
    types: [ opened, edited, reopened, synchronize ]

jobs:
  fix-formatting:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          cache: npm

      - run: npm ci

      - run: npx eslint . --fix

      - name: Setup GPG commit verification
        uses: crazy-max/ghaction-import-gpg@111c56156bcc6918c056dbef52164cfa583dc549 # v5.2.0
        with:
          gpg_private_key: ${{ secrets.BOT_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.BOT_GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - uses: stefanzweifel/git-auto-commit-action@8756aa072ef5b4a080af5dc8fef36c5d586e521d # v5.0.0
        with:
          commit_message: Formatting changes
          commit_user_name: probation-integration-bot
          commit_user_email: probation-integration-team@digital.justice.gov.uk
          commit_author: probation-integration-bot <probation-integration-team@digital.justice.gov.uk>
