name: Test Data Generator

on:
  workflow_dispatch:
    inputs:
      project:
        description: Project
        type: choice
        required: true
        options:
          - approved-premises-data-creator
          - effective-proposal-framework
          - refer-and-monitor-functional-tests
    outputs:
      report-url:
        description: The URL of the Playwright HTML report
        value: ${{ jobs.test.outputs.report-url }}

jobs:
  test:
    runs-on: moj-cloud-platform
    timeout-minutes: 20
    outputs:
      report-url: ${{ steps.html.outputs.report-url }}
    steps:
      - uses: actions/checkout@v3
      - name: Get report output directory
        run: echo "report-dir=playwright-report/test/$REF/$(date '+%Y-%m-%d')/${{ github.sha }}/${{ github.run_id }}/${{ github.run_attempt }}" | tee -a "$GITHUB_ENV"
        env:
          REF: ${{ github.ref_name }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install
      - name: Run Playwright tests
        id: tests
        run: npx playwright test --reporter=html,junit,json,line --workers=8
        env:
          TEST_DIR: ./test-data-setup/${{ inputs.project }}
          TZ: Europe/London
          ENV: test
          DELIUS_URL: https://ndelius.test.probation.service.justice.gov.uk
          WORKFORCE_URL: https://workforce-management-dev.hmpps.service.justice.gov.uk
          DPS_URL: https://digital-dev.prison.service.justice.gov.uk
          AUTH_URL: https://sign-in-dev.hmpps.service.justice.gov.uk
          PRISON_API: https://prison-api-dev.prison.service.justice.gov.uk
          EPF_API: https://effective-proposal-framework-and-delius-dev.hmpps.service.justice.gov.uk
          EXTERNAL_API: https://external-api-and-delius-dev.hmpps.service.justice.gov.uk
          REFERANDMONITOR_URL: https://hmpps-interventions-ui-dev.apps.live-1.cloud-platform.service.justice.gov.uk
          OASYS_URL: https://t2.oasys.service.justice.gov.uk/eor/f?p=100:101
          APPROVEDPREMISES_URL: https://approved-premises-dev.hmpps.service.justice.gov.uk
          CONSIDER_A_RECALL_URL: https://consider-a-recall-dev.hmpps.service.justice.gov.uk
          MANAGE_POM_CASES_URL: https://dev.moic.service.justice.gov.uk
          DELIUS_USERNAME: ${{ secrets.E2E_DELIUS_USERNAME }}
          DELIUS_PASSWORD: ${{ secrets.E2E_DELIUS_PASSWORD }}
          DPS_USERNAME: ${{ secrets.E2E_DPS_USERNAME }}
          DPS_PASSWORD: ${{ secrets.E2E_DPS_PASSWORD }}
          CRED_USERNAME: ${{ secrets.E2E_CLIENT_ID }}
          CRED_PASSWORD: ${{ secrets.E2E_CLIENT_SECRET }}
          REFERANDMONITOR_SUPPLIER_USERNAME: ${{ secrets.E2E_REFERANDMONITOR_SUPPLIER_USERNAME }}
          REFERANDMONITOR_SUPPLIER_PASSWORD: ${{ secrets.E2E_REFERANDMONITOR_SUPPLIER_PASSWORD }}
          OASYS_USERNAME_BOOKING: ${{ secrets.E2E_OASYS_USERNAME_BOOKING }}
          OASYS_PASSWORD_BOOKING: ${{ secrets.E2E_OASYS_PASSWORD_BOOKING }}
          OASYS_USERNAME_RSR: ${{ secrets.E2E_OASYS_USERNAME_RSR }}
          OASYS_PASSWORD_RSR: ${{ secrets.E2E_OASYS_PASSWORD_RSR }}
          OASYS_USERNAME_TIMELINE: ${{ secrets.E2E_OASYS_USERNAME_TIMELINE }}
          OASYS_PASSWORD_TIMELINE: ${{ secrets.E2E_OASYS_PASSWORD_TIMELINE }}
          APPROVEDPREMISES_USERNAME: ${{ secrets.E2E_DELIUS_USERNAME }}
          APPROVEDPREMISES_PASSWORD: ${{ secrets.E2E_DELIUS_PASSWORD }}
          CONSIDER_A_RECALL_MRD_USERNAME: ${{ secrets.E2E_CONSIDER_RECALL_MRD_USERNAME }}
          CONSIDER_A_RECALL_MRD_PASSWORD: ${{ secrets.E2E_CONSIDER_RECALL_MRD_PASSWORD }}
          CONSIDER_RECALL_MRD_PASSWORD: ${{ secrets.E2E_CONSIDER_RECALL_MRD_PASSWORD }}
          PLAYWRIGHT_JUNIT_OUTPUT_NAME: junit.xml
          PLAYWRIGHT_JSON_OUTPUT_NAME: results.json
      - name: Publish HTML report
        uses: JamesIves/github-pages-deploy-action@22a6ee251d6f13c6ab1ecb200d974f1a6feb1b8d # v4
        with:
          folder: playwright-report
          target-folder: ${{ env.report-dir }}
      - name: Output HTML report URL
        id: html
        run: |
          echo '[🎭 Playwright HTML Report](https://ministryofjustice.github.io/hmpps-probation-integration-e2e-tests/${{ env.report-dir }})' | tee -a "$GITHUB_STEP_SUMMARY"
          echo 'report-url=https://ministryofjustice.github.io/hmpps-probation-integration-e2e-tests/${{ env.report-dir }}' | tee -a "$GITHUB_OUTPUT"
