name: '* Setup test data'

on:
  workflow_dispatch:
    inputs:
      create_delius:
        description: Create a Delius record?
        type: boolean
        default: true
        required: true
      create_nomis:
        description: Create a NOMIS record?
        type: boolean
        default: true
        required: true
      create_assessment:
        description: Create an OASys assessment?
        type: boolean
        default: false
        required: true
      create_hearing:
        description: Create a court hearing?
        type: boolean
        default: false
        required: true
      allocate_to_user:
        description: Allocate to specific user? (Provide details below)
        type: boolean
        default: false
        required: false
      allocation_provider:
        description: Allocation - Provider (eg, London)
        type: string
        required: false
        default: ""
      allocation_team:
        description: Allocation - Team  (eg, OMU B)
        type: string
        required: false
        default: ""
      allocation_first_name:
        description: Allocation - Officer's forename
        type: string
        required: false
        default: ""
      allocation_last_name:
        description: Allocation - Officer's surname
        type: string
        required: false
        default: ""
      project:
        description: Or, create data for a specific project
        type: choice
        required: true
        options:
          - none
          - approved-premises-data-creator
          - consider-a-recall-data-creator
          - effective-proposal-framework
          - recommend-a-recall
          - refer-and-monitor-functional-tests
          - hmpps-integration-api
          - create-case-with-unpaid-work-allocation
          - create-unallocated-workforce-cases
          - create-unallocated-case-with-documents
          - single-accommodation-service

jobs:
  create-generic-data:
    uses: ./.github/workflows/test.yml
    if: inputs.project == 'none'
    with:
      directory: test-data-setup
      projects: '["create-generic-case"]'
      workers: 1
      env: |
        {
          "CREATE_DELIUS_RECORD": "${{ inputs.create_delius }}",
          "CREATE_NOMIS_RECORD": "${{ inputs.create_nomis }}",
          "CREATE_OASYS_ASSESSMENT": "${{ inputs.create_assessment }}",
          "CREATE_COURT_HEARING": "${{ inputs.create_hearing }}",
          "ALLOCATE_TO_USER": "${{ inputs.allocate_to_user }}",
          "ALLOCATION_PROVIDER": "${{ inputs.allocation_provider }}",
          "ALLOCATION_TEAM": "${{ inputs.allocation_team }}",
          "ALLOCATION_FIRST_NAME": "${{ inputs.allocation_first_name }}",
          "ALLOCATION_LAST_NAME": "${{ inputs.allocation_last_name }}"
        }
    secrets: inherit

  create-for-project:
    uses: ./.github/workflows/test.yml
    if: inputs.project != 'none'
    with:
      directory: test-data-setup
      projects: '["${{ inputs.project }}"]'
      workers: 1
    secrets: inherit
