name: '* Run tests'

on:
  # Run manually via GitHub UI
  workflow_dispatch:
    inputs:
      projects:
        description: Project
        type: choice
        required: true
        options:
          - 'All'
          - '["approved-premises-and-delius"]'
          - '["approved-premises-and-oasys"]'
          - '["court-case-and-delius"]'
          - '["create-and-vary-a-licence-and-delius"]'
          - '["custody-key-dates-and-delius"]'
          - '["domain-events-and-delius"]'
          - '["effective-proposal-framework-and-delius"]'
          - '["external-api-and-delius"]'
          - '["make-recall-decisions-and-delius"]'
          - '["manage-pom-cases-and-delius"]'
          - '["offender-events-and-delius"]'
          - '["pathfinder-and-delius"]'
          - '["person-search-index-from-delius"]'
          - '["pre-sentence-reports-to-delius"]'
          - '["prison-case-notes-to-probation"]'
          - '["prison-custody-status-to-delius"]'
          - '["refer-and-monitor-and-delius"]'
          - '["risk-assessment-scores-to-delius"]'
          - '["sentence-plan-and-delius"]'
          - '["sentence-plan-and-oasys"]'
          - '["soc-and-delius"]'
          - '["tier-to-delius"]'
          - '["unpaid-work-and-delius"]'
          - '["workforce-allocations-to-delius"]'
          - '["manage-offences-and-delius"]'
          - '["resettlement-passport-and-delius"]'
          - '["prison-education-and-delius"]'
          - '["opd-and-delius"]'
          - '["hmpps-auth-and-delius"]'
          - '["dps-and-delius"]'
          - '["arns-and-delius"]'
          - '["cas3-and-delius"]'
          - '["hdc-licences-and-delius"]'
          - '["prisoner-profile-and-delius"]'
          - '["prison-identifier-and-delius"]'
          - '["assessment-summary-and-delius"]'
          - '["accredited-programmes-and-oasys"]'
          - '["cas2-and-delius"]'
          - '["manage-supervision-and-oasys"]'
          - '["manage-supervision-and-delius"]'
          - '["oasys-and-delius"]'
          - '["probation-search-and-delius"]'
          - '["core-person-record-and-delius"]'
          - '["subject-access-requests-and-delius"]'
          - '["common-platform-and-delius"]'
          - '["ims-and-delius"]'
          # ^ add new projects here
          # GitHub Actions doesn't support dynamic choices, we must add each project here to enable manual deployments
          # See https://github.com/community/community/discussions/11795

jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      projects: ${{ inputs.projects }}
    secrets: inherit
