name: End-to-end tests (remote)
# A re-usable workflow for running end-to-end tests remotely from other repositories.

on:
  workflow_call:
    inputs:
      projects:
        description: A JSON array of projects to deploy e.g. '["approved-premises-and-delius"]'
        type: string
        required: true
    secrets:
      token:
        description: A GitHub personal access token, with "actions:write" permissions to trigger a workflow run in the hmpps-probation-integration-e2e-tests repository
        required: true
    outputs:
      failed-projects:
        description: A JSON array of projects that failed end-to-end testing
        value: ${{ jobs.test.outputs.failed-projects }}
      passed-projects:
        description: A JSON array of projects that passed end-to-end testing
        value: ${{ jobs.test.outputs.passed-projects }}
      report-url:
        description: The URL of the Playwright HTML report
        value: ${{ jobs.test.outputs.report-url }}

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    outputs:
      failed-projects: ${{ steps.run.outputs.failed-projects }}
      passed-projects: ${{ steps.run.outputs.passed-projects }}
      report-url: ${{ steps.run.outputs.report-url }}
    steps:
      - id: run
        uses: ./.github/actions/run-tests
        with:
          projects: ${{ inputs.projects }}
          token: ${{ secrets.token }}
